/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/calendar.module';
import * as i2 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as i3 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as i4 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as i5 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as i6 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as i7 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as i8 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as i9 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as i10 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as i11 from './components/calendar.modal.ngfactory';
import * as i12 from './components/calendar-week.component.ngfactory';
import * as i13 from './components/month.component.ngfactory';
import * as i14 from './components/calendar.component.ngfactory';
import * as i15 from './components/month-picker.component.ngfactory';
import * as i16 from '@angular/common';
import * as i17 from '@angular/forms';
import * as i18 from '../../src/services/calendar.service';
import * as i19 from '../../src/calendar.controller';
import * as i20 from 'ionic-angular/components/modal/modal-controller';
import * as i21 from 'ionic-angular/module';
export const CalendarModuleNgFactory:i0.NgModuleFactory<i1.CalendarModule> = i0.ɵcmf(i1.CalendarModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ActionSheetCmpNgFactory,i3.AlertCmpNgFactory,i4.IonicAppNgFactory,
              i5.LoadingCmpNgFactory,i6.ModalCmpNgFactory,i7.PickerCmpNgFactory,i8.PopoverCmpNgFactory,
              i9.SelectPopoverNgFactory,i10.ToastCmpNgFactory,i11.CalendarModalNgFactory,
              i12.CalendarWeekComponentNgFactory,i13.MonthComponentNgFactory,i14.CalendarComponentNgFactory,
              i15.MonthPickerComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i16.NgLocalization,i16.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i17.ɵi,i17.ɵi,([] as any[])),i0.ɵmpd(4608,i17.FormBuilder,
          i17.FormBuilder,([] as any[])),i0.ɵmpd(4608,i18.CalendarService,i18.CalendarService,
          ([] as any[])),i0.ɵmpd(5120,i19.CalendarController,i1.calendarController,
          [i20.ModalController,i18.CalendarService]),i0.ɵmpd(512,i16.CommonModule,
          i16.CommonModule,([] as any[])),i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),
          i0.ɵmpd(512,i17.FormsModule,i17.FormsModule,([] as any[])),i0.ɵmpd(512,i17.ReactiveFormsModule,
              i17.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i21.IonicModule,i21.IonicModule,
              ([] as any[])),i0.ɵmpd(512,i1.CalendarModule,i1.CalendarModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pzYW5jaGV6L0NvY2t0YWlMYWJzL2lvbjItY2FsZW5kYXIvc3JjL2NhbGVuZGFyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qc2FuY2hlei9Db2NrdGFpTGFicy9pb24yLWNhbGVuZGFyL3NyYy9jYWxlbmRhci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
