/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as i2 from 'ionic-angular/components/toolbar/toolbar';
import * as i3 from 'ionic-angular/config/config';
import * as i4 from '@angular/common';
import * as i5 from '../../../src/components/calendar-week.component';
const styles_CalendarWeekComponent:any[] = ([] as any[]);
export const RenderType_CalendarWeekComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CalendarWeekComponent,data:{}});
function View_CalendarWeekComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_CalendarWeekComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),8,'ion-toolbar',[['class','week-toolbar toolbar'],['no-border-top',
          '']],[[2,'statusbar-padding',(null as any)]],(null as any),(null as any),
      i1.View_Toolbar_0,i1.RenderType_Toolbar)),i0.ɵdid(49152,(null as any),0,i2.Toolbar,
      [i3.Config,i0.ElementRef,i0.Renderer],(null as any),(null as any)),(_l()(),i0.ɵted(3,
      ['\n      '])),(_l()(),i0.ɵeld(0,(null as any),3,4,'ul',([] as any[]),[[8,'className',
      0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n        '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_CalendarWeekComponent_1)),i0.ɵdid(802816,(null as any),0,i4.NgForOf,[i0.ViewContainerRef,
      i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),
      i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵted(3,['\n    '])),(_l()(),
      i0.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    var _co:i5.CalendarWeekComponent = _v.component;
    const currVal_2:any = _co._weekArray;
    _ck(_v,7,0,currVal_2);
  },(_ck,_v) => {
    var _co:i5.CalendarWeekComponent = _v.component;
    const currVal_0:any = i0.ɵnov(_v,2)._sbPadding;
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = ('week-title ' + _co.color);
    _ck(_v,4,0,currVal_1);
  });
}
export function View_CalendarWeekComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ion-calendar-week',
      ([] as any[]),(null as any),(null as any),(null as any),View_CalendarWeekComponent_0,
      RenderType_CalendarWeekComponent)),i0.ɵdid(49152,(null as any),0,i5.CalendarWeekComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const CalendarWeekComponentNgFactory:i0.ComponentFactory<i5.CalendarWeekComponent> = i0.ɵccf('ion-calendar-week',
    i5.CalendarWeekComponent,View_CalendarWeekComponent_Host_0,{color:'color',weekArray:'weekArray',
        weekStart:'weekStart'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pzYW5jaGV6L0NvY2t0YWlMYWJzL2lvbjItY2FsZW5kYXIvc3JjL2NvbXBvbmVudHMvY2FsZW5kYXItd2Vlay5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvanNhbmNoZXovQ29ja3RhaUxhYnMvaW9uMi1jYWxlbmRhci9zcmMvY29tcG9uZW50cy9jYWxlbmRhci13ZWVrLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2pzYW5jaGV6L0NvY2t0YWlMYWJzL2lvbjItY2FsZW5kYXIvc3JjL2NvbXBvbmVudHMvY2FsZW5kYXItd2Vlay5jb21wb25lbnQudHMuQ2FsZW5kYXJXZWVrQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9qc2FuY2hlei9Db2NrdGFpTGFicy9pb24yLWNhbGVuZGFyL3NyYy9jb21wb25lbnRzL2NhbGVuZGFyLXdlZWsuY29tcG9uZW50LnRzLkNhbGVuZGFyV2Vla0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxpb24tdG9vbGJhciBjbGFzcz1cIndlZWstdG9vbGJhclwiIG5vLWJvcmRlci10b3A+XG4gICAgICA8dWwgW2NsYXNzXT1cIid3ZWVrLXRpdGxlICcgKyBjb2xvclwiPlxuICAgICAgICA8bGkgKm5nRm9yPVwibGV0IHcgb2YgX3dlZWtBcnJheVwiPnt7d319PC9saT5cbiAgICAgIDwvdWw+XG4gICAgPC9pb24tdG9vbGJhcj5cbiAgIiwiPGlvbi1jYWxlbmRhci13ZWVrPjwvaW9uLWNhbGVuZGFyLXdlZWs+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0dRO01BQUEsd0VBQWlDO2FBQUE7SUFBQTtJQUFBOzs7O29CQUh6QywyQ0FDSTtNQUFBO1VBQUE7NkNBQUEsVUFBQTtNQUFBLG1FQUFnRDtNQUFBLGVBQzlDO01BQUEsOERBQW9DO01BQUEsaUJBQ2xDO01BQUEsc0NBQUE7dUNBQUEseUNBQTJDO2FBQUEsOEJBQ3hDLCtCQUNPO2FBQUE7O0lBRk47SUFBSixXQUFJLFNBQUo7OztJQUZKO0lBQUEsV0FBQSxTQUFBO0lBQ007SUFBSixXQUFJLFNBQUo7Ozs7b0JDRk47TUFBQTtzQ0FBQSxVQUFBO01BQUE7Ozs7In0=
